source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'unicorn'
gem 'redis'

group :development do
  gem 'rack-mini-profiler'
  #gem 'rack-lineprof'
  gem 'rack-lineprof'
  gem 'stackprof'
  gem 'foreman'
  gem 'sinatra-contrib', require: nil
end
